### ISSUE TITLE
JSON episode: Write the JSON file to csv needs reworking

### ISSUE THREAD

**Issue by jessesadler** [datacarpentry/r-socialsci#448] opened 2023-04-14 16:42 UTC
Writing a dataframe with list columns to file with `wrote_csv()` does not create an error.

The process of flattening the list columns could also use updating.

**Comment by rsangole** [comment] 2023-05-04 06:29
I'm searching for a first issue to resolve. Does this still need attention?

**Comment by juanfung** [comment] 2023-05-04 14:27
@rsangole yes, it would be great if you would like to submit a PR to address this issue!

**Comment by rsangole** [comment] 2023-05-04 16:28
Great. @juanfung could you elaborate on what the issue is?

**Comment by rsangole** [comment] 2023-05-06 04:22
https://github.com/datacarpentry/r-socialsci/pull/458

**Comment by juanfung** [comment] 2023-05-08 16:02
@rsangole apologies, just saw your question. i didn't open the issue, but to me it looks like it is resolved by your PR. i will defer to @jessesadler

**Closed** 2023-05-15 17:59 UTC
Labels: help wanted, good first issue
